import warnings
from typing import Optional

import numpy as np

from qemcmc.circuits import CircuitMaker
from qemcmc.coarse_grain import CoarseGraining
from qemcmc.model import EnergyModel
from qemcmc.sampler import Proposal

warnings.filterwarnings("ignore", category=RuntimeWarning)


class QeProposal(Proposal):
    """
    Quantum-enhanced Markov Chain Monte Carlo sampler.

    This class implements the proposal mechanism of the quantum-enhanced
    MCMC algorithm. Candidate states are generated by simulating the
    quantum time evolution of a transverse-field Hamiltonian. 

    The quantum proposal circuit is constructed using :class:`CircuitMaker`
    and can optionally operate on coarse-grained subgroups of spins to
    improve scalability.

    Parameters
    ----------
    model : EnergyModel
        Energy model defining the target Boltzmann distribution.
    gamma : float | tuple[float, float]
        Transverse field strength (Γ). If a tuple is provided, a value is
        sampled uniformly from the range [min, max] at each step.
    time : int | tuple[int, int]
        Number of Trotter steps. If a tuple is provided, the number of steps
        is randomly sampled from the range [min, max].
    delta_time : float, optional
        Duration of each Trotter step (δt), by default 0.8.
    coarse_graining : CoarseGraining | None, optional
        A coarse-graining scheme to define spin subgroups. If None, no coarse-graining
        is used. By default None.
    coupling_weights : list[float | tuple[float, float]] | None, optional
        Weights for the coupling tensors. If a tuple is provided, a weight is
        sampled uniformly from the range. This allows for dynamic adjustment
        of the influence of different terms in the Hamiltonian during the proposal
        step. By default None.
        Note that this is further adjusted by (1 - gamma) to balance the influence of the 
        problem Hamiltonian with the mixer term. Divide by (1 - gamma) if needed.
    m : int, optional
        Number of subgroups to partition the spins into for sequential updates.
        By default 1.

    Notes
    -----
    The proposal step simulates the time evolution under a transverse-field Hamiltonian defined by the energy model
    and measures the resulting state to produce a candidate configuration.
    This proposal is then accepted or rejected using the Metropolis criterion
    to ensure convergence to the target Boltzmann distribution.
    """

    def __init__(
        self,
        model: EnergyModel,
        gamma: float | tuple[float, float],
        time: int | tuple[int, int],
        delta_time: float = 0.8,
        coarse_graining: Optional[CoarseGraining] = None,
        coupling_weights: Optional[list[float | tuple[float, float]]] = None,
        m: int = 1,
    ):
        super().__init__(model)

        if coupling_weights is not None:
            if len(coupling_weights) != len(model.normalised_couplings):
                raise ValueError(
                    f"Length of coupling_weights ({len(coupling_weights)}) must match the number of "
                    f"couplings in the model ({len(model.normalised_couplings)}), including constraint terms."
                )
            self.coupling_weights = coupling_weights
        else:
            self.coupling_weights = list(np.ones(len(model.normalised_couplings)))

        self.gamma = self._validate_gamma(gamma)
        self.time = self._validate_time(time)
        self.delta_time = delta_time
        self.m = m
        self.method = "quantum"

        self.CM = CircuitMaker(self.model, delta_time=self.delta_time)

        
        self.cg = coarse_graining or CoarseGraining(model.n_spins)

    def update(self, current_state: str) -> str:
        """
        Perform 'm' sequential quantum updates across non-overlapping subgroups.

        Parameters
        ----------
        current_state : str
            Current state of the system as a bitstring.

        Returns
        -------
        str
            Updated state of the system as a bitstring.

        """
        if not isinstance(current_state, str):
            raise TypeError(f"Bitstring must be of type str, got {type(current_state)}: {current_state!r}")

        

        # Generate m disjoint partitions of the spins
        partitions = self.cg.get_partitions(m=self.m)
        
        final_coupling_weights, g, t = self.sample_hyperparams()




        working_state = current_state
        for subgroup in partitions:
            # Recalculate local couplings as spins outside the subgroup may have flipped
            local_couplings = self.model.get_subgroup_couplings(
                subgroup=subgroup,
                current_state=working_state,
                coupling_weights=final_coupling_weights
            )
            working_state = self.CM.update(
                s=working_state,
                subgroup_choice=subgroup,
                local_couplings=local_couplings,
                gamma=g,
                time=t
            )
        return working_state
    
    def sample_hyperparams(self) -> tuple[list[float], float, int]:
        """
        Sample coupling weights for the current proposal step based on the provided coupling_weights configuration.
        """
        # Sample gamma and time once per full proposal step
        g = self.gamma if not isinstance(self.gamma, tuple) else np.random.uniform(*self.gamma)
        t = self.time if not isinstance(self.time, tuple) else np.random.randint(self.time[0], self.time[1] + 1)

        # Pre-sample weights for all unique coupling weight settings (tuples or floats)
        unique_items = sorted(list(set(self.coupling_weights)), key=lambda x: str(x))
        unique_index = [[i for i, x in enumerate(self.coupling_weights) if x == item] for item in unique_items]
        
        sampled_weights = np.ones(len(unique_items), dtype=float)
        for i, item in enumerate(unique_items):
            if isinstance(item, (int, float)):
                sampled_weights[i] = item
            elif isinstance(item, tuple):
                sampled_weights[i] = np.random.uniform(*item)

        # Adjust the sampled weights by (1 - gamma) to balance their influence with the mixer term in the Hamiltonian
        sampled_weights_adjusted_by_gamma = (1-g) * sampled_weights  # Adjust weights by (1 - gamma) to balance with the mixer term

        # Construct the final list of coupling weights for this update step
        final_coupling_weights = np.ones(len(self.coupling_weights))
        for i, indices in enumerate(unique_index):
            for index in indices:
                final_coupling_weights[index] = sampled_weights_adjusted_by_gamma[i]

        
        return final_coupling_weights, g, t

    def _validate_gamma(self, gamma: float | tuple[float, float]) -> float | tuple[float, float]:
        """
        Validates the transverse field strength gamma (Γ).
        """
        if isinstance(gamma, (float, int)):
            if not (0.0 <= gamma <= 1.0):
                raise ValueError(f"gamma must be in [0, 1], got {gamma}")
            return float(gamma)

        if isinstance(gamma, (tuple, list)):
            if len(gamma) != 2:
                raise ValueError(f"gamma tuple or list must be (min, max), got {gamma}")
            g_min, g_max = gamma
            if not (0.0 <= g_min <= g_max <= 1.0):
                raise ValueError(f"gamma range must satisfy 0 <= min <= max <= 1, got {gamma}")
            return (float(g_min), float(g_max))

        raise TypeError(f"gamma must be a float or tuple[float, float] or list[float, float] got {type(gamma)}")

    def _validate_time(self, time: int | tuple[int, int]) -> int | tuple[int, int]:
        """
        Validates the number of Trotter steps.
        """
        if isinstance(time, int):
            if time <= 0:
                raise ValueError(f"time must be a positive integer, got {time}")
            return time

        if isinstance(time, tuple):
            if len(time) != 2:
                raise ValueError(f"time tuple must be (min, max), got {time}")
            t_min, t_max = time
            if not (isinstance(t_min, int) and isinstance(t_max, int)):
                raise TypeError(f"time range must contain integers, got {time}")
            if t_min <= 0 or t_max <= 0:
                raise ValueError(f"time values must be positive, got {time}")
            if t_min > t_max:
                raise ValueError(f"time range must satisfy min <= max, got {time}")
            return (t_min, t_max)

        raise TypeError(f"time must be an int or tuple[int, int], got {type(time)}")
