name: Publish qemcmc to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: pypi

    permissions:
      id-token: write  # for trusted publishing

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build tool
        run: pip install build

      - name: Build
        run: python -m build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1